usedcars <- read.csv("usedcars.csv", stringsAsFactors = FALSE)
str(usedcars) 
summary(usedcars$year)
summary(usedcars[c("price", "mileage")])
range(usedcars$price)
diff(range(usedcars$price))
quantile(usedcars$price, seq(from = 0, to = 1, by = 0.20))
table(usedcars$year)
table(usedcars$model)
table(usedcars$color)
model_table <- table(usedcars$model)
prop.table(model_table)
color_pct <- table(usedcars$color)
color_pct <- prop.table(color_pct) * 100
round(color_pct, digits = 1)
getwd()
